method: bayes
metric:
  name: test_returns
  goal: maximize
parameters:
  LR:
    values: [0.0001, 0.0005, 0.001, 0.005]
  EPS_ADAM:
    values: [0.00000001, 0.000001, 0.00001, 0.0001]
  NUM_ENVS:
    values: [4, 8, 16]
  BUFFER_SIZE:
    values: [512, 1024, 2048]
  MIXER_EMBEDDING_DIM:
    values: [16, 32, 64]
  EPSILON_START:
    values: [0.9, 1.0, 1.1]
  EPSILON_FINISH:
    values: [0.01, 0.05, 0.1]
  EPSILON_ANNEAL_TIME:
    values: [1e6, 0.5e6, 1e6]
  AGENT_HIDDEN_DIM:
    values: [32, 64, 128]
  AGENT_INIT_SCALE:
    values: [1.0, 2.0, 3.0]
  NUM_STEPS:
    values: [128, 256]
