"NUM_ENVS": 8
"NUM_STEPS": 128
"BUFFER_SIZE": 1024
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 5e6 

"AGENT_HIDDEN_DIM": 64
"AGENT_INIT_SCALE": 3
"PARAMETERS_SHARING": True
"EPSILON_START": 0.9
"EPSILON_FINISH": 0.1
"EPSILON_ANNEAL_TIME": 5e5
"MIXER_EMBEDDING_DIM": 64
"MIXER_HYPERNET_HIDDEN_DIM": 128
"MIXER_INIT_SCALE": 0.0001
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 100
"LR": 0.0005
"LR_LINEAR_DECAY": False
"EPS_ADAM": 0.000001
"WEIGHT_DECAY_ADAM": 0.0001
"TD_LAMBDA_LOSS": False
"TD_LAMBDA": 0.7
"GAMMA": 0.99
"VERBOSE": False
"WANDB_ONLINE_REPORT": True
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 50000